"""Tests for the qvalue module."""

import numpy as np
import pandas as pd
import pytest
from pathlib import Path

from shackett_utils.statistics.qvalue import (
    estimate_pi0,
    estimate_lfdr,
    estimate_qvalues,
)


@pytest.fixture(scope="module")
def r_results():
    """
    Load R qvalue reference results generated by:

        set.seed(42)
        n_null <- 320; n_alt <- 80
        p_null <- runif(n_null); p_alt <- rbeta(n_alt, 0.05, 1)
        pvals  <- pmax(c(p_null, p_alt), 1e-8)
        pi0_r  <- pi0est(pvals)$pi0
        data.frame(
            pvalue = pvals,
            pi0    = pi0_r,
            lfdr   = lfdr(pvals, pi0 = pi0_r),
            qvalue = qvalue(pvals, pi0 = pi0_r)$qvalues
        )

    The CSV lives alongside this test file so the path is always
    resolved relative to it, regardless of where pytest is invoked.
    """
    path = Path(__file__).parent / "data" / "qvalue_r_results.csv"
    df = pd.read_csv(path)
    return df


@pytest.fixture(scope="module")
def pvals(r_results):
    return r_results["pvalue"].to_numpy()


@pytest.fixture(scope="module")
def pi0_r(r_results):
    # pi0 is constant across all rows — a single scalar from R
    values = r_results["pi0"].unique()
    assert len(values) == 1, "Expected a single pi0 value across all rows"
    return float(values[0])


@pytest.fixture(scope="module")
def lfdr_r(r_results):
    return r_results["lfdr"].to_numpy()


@pytest.fixture(scope="module")
def qvalue_r(r_results):
    return r_results["qvalue"].to_numpy()


def test_pi0_close_to_r(pvals, pi0_r):
    """
    Tolerance of 0.05 reflects the known difference between scipy's
    splrep (residual penalty) and R's smooth.spline (GCV-based effective
    df). The spline smoothing step is the sole source of divergence here.
    """
    pi0_py = estimate_pi0(pvals)
    assert abs(pi0_py - pi0_r) < 0.05, (
        f"pi0 mismatch: Python={pi0_py:.6f}, R={pi0_r:.6f}, "
        f"diff={abs(pi0_py - pi0_r):.6f}"
    )


def test_pi0_in_valid_range(pvals):
    pi0_py = estimate_pi0(pvals)
    assert 0 < pi0_py <= 1.0


def test_pi0_rejects_nans():
    with pytest.raises(ValueError, match="NaN"):
        estimate_pi0(np.array([0.1, np.nan, 0.5]))


def test_pi0_rejects_out_of_range():
    with pytest.raises(ValueError):
        estimate_pi0(np.array([0.1, 0.5, 1.5]))


def test_pi0_all_tiny_p_appends_synthetic_for_grid():
    """When every p is below the default lambda grid, pi0 still runs (tail pad)."""
    p_tiny = np.array([1e-20, 1e-22, 3e-19])
    pi0 = estimate_pi0(p_tiny)
    assert 0 < pi0 <= 1.0


def test_lfdr_correlation_with_r(pvals, pi0_r, lfdr_r):
    """
    Correlation is tight at 0.9998 on reference data. Threshold of
    0.999 gives a small margin while catching any real regression.
    """
    lfdr_py = estimate_lfdr(pvals, pi0=pi0_r)
    corr = np.corrcoef(lfdr_py, lfdr_r)[0, 1]
    assert corr > 0.999, f"lfdr correlation too low: {corr:.6f}"


def test_lfdr_max_abs_diff_with_r(pvals, pi0_r, lfdr_r):
    """
    Max abs diff is 0.051 on reference data; threshold of 0.06 gives
    a small margin. Residual divergence comes from scipy's splrep vs
    R's smooth.spline applied to the KDE grid.
    """
    lfdr_py = estimate_lfdr(pvals, pi0=pi0_r)
    max_diff = np.abs(lfdr_py - lfdr_r).max()
    assert max_diff < 0.06, f"lfdr max abs diff {max_diff:.6f} exceeds tolerance"


def test_lfdr_mean_abs_diff_with_r(pvals, pi0_r, lfdr_r):
    """
    Mean abs diff is 0.004 on reference data — typical errors are much
    smaller than the max. Threshold of 0.01 catches systematic bias
    while allowing the known tail divergence.
    """
    lfdr_py = estimate_lfdr(pvals, pi0=pi0_r)
    mean_diff = np.abs(lfdr_py - lfdr_r).mean()
    assert mean_diff < 0.01, f"lfdr mean abs diff {mean_diff:.6f} exceeds tolerance"


def test_lfdr_in_valid_range(pvals, pi0_r):
    lfdr_py = estimate_lfdr(pvals, pi0=pi0_r)
    assert np.all(lfdr_py >= 0), "lfdr contains negative values"
    assert np.all(lfdr_py <= 1), "lfdr contains values > 1 (trunc should prevent this)"


def test_lfdr_monotone_with_pvalue(pvals, pi0_r):
    """
    With monotone=True (default), lfdr should be non-decreasing
    with p-value rank — larger p-values can't have smaller lfdr.
    """
    lfdr_py = estimate_lfdr(pvals, pi0=pi0_r)
    order = np.argsort(pvals)
    lfdr_sorted = lfdr_py[order]
    assert np.all(
        np.diff(lfdr_sorted) >= -1e-10
    ), "lfdr is not monotone non-decreasing with p-value"


def test_lfdr_rejects_nans():
    with pytest.raises(ValueError, match="NaN"):
        estimate_lfdr(np.array([0.1, np.nan, 0.5]))


def test_qvalues_close_to_r(pvals, pi0_r, qvalue_r):
    """
    Q-values are floating-point identical to R given the same pi0 —
    the calculation is a deterministic rank operation with no numerical
    approximation. Tolerance of 1e-10 reflects this.
    """
    qvals_py = estimate_qvalues(pvals, pi0=pi0_r)
    max_diff = np.abs(qvals_py - qvalue_r).max()
    assert max_diff < 1e-10, f"qvalue max abs diff {max_diff:.2e} exceeds tolerance"


def test_qvalues_in_valid_range(pvals, pi0_r):
    qvals_py = estimate_qvalues(pvals, pi0=pi0_r)
    assert np.all(qvals_py >= 0)
    assert np.all(qvals_py <= 1)


def test_qvalues_monotone_with_pvalue(pvals, pi0_r):
    """
    Q-values must be non-decreasing with p-value rank by construction
    of the BH cumulative minimum step.
    """
    qvals_py = estimate_qvalues(pvals, pi0=pi0_r)
    order = np.argsort(pvals)
    qvals_sorted = qvals_py[order]
    assert np.all(
        np.diff(qvals_sorted) >= -1e-10
    ), "q-values are not monotone non-decreasing with p-value"


def test_qvalues_bounded_by_pi0(pvals, pi0_r):
    """
    Max q-value cannot exceed pi0 — a consequence of the BH
    cumulative min being bounded above by pi0 * 1.
    """
    qvals_py = estimate_qvalues(pvals, pi0=pi0_r)
    assert (
        qvals_py.max() <= pi0_r + 1e-10
    ), f"max q-value {qvals_py.max():.4f} exceeds pi0 {pi0_r:.4f}"


def test_qvalues_rejects_nans():
    with pytest.raises(ValueError, match="NaN"):
        estimate_qvalues(np.array([0.1, np.nan, 0.5]))
